<script>
  import Header from '$lib/components/Header.svelte';
</script>

<svelte:head>
  <title>Privacy Policy - Holmes AI</title>
  <meta name="description" content="Learn how Holmes AI protects your privacy and handles your data. We are committed to keeping your spiritual conversations secure and confidential." />
</svelte:head>

<div class="privacy-page">
  <Header />
  
  <!-- Hero Section -->
  <section class="hero" role="banner">
    <div class="hero-content">
      <h1>Privacy Policy</h1>
      <p class="hero-subtitle">How We Protect Your Privacy and Data</p>
    </div>
  </section>

  <div class="container">
    <!-- Introduction -->
    <section class="section" aria-labelledby="intro-heading">
      <div class="intro-content">
        <p class="lead">
          At Holmes AI, we understand that spiritual conversations are deeply personal and sacred. 
          We are committed to protecting your privacy and ensuring the confidentiality of your interactions with our AI.
        </p>
        <p>
          This Privacy Policy explains how we collect, use, and protect your information when you use Holmes AI. 
          By using our service, you agree to the collection and use of information in accordance with this policy.
        </p>
      </div>
    </section>

    <!-- Information We Collect -->
    <section class="section" aria-labelledby="collect-heading">
      <h2 id="collect-heading">Information We Collect</h2>
      <div class="policy-content">
        <div class="policy-item">
          <h3>Conversation Data</h3>
          <p>
            We collect the questions you ask and the responses generated by Holmes AI. This includes:
          </p>
          <ul>
            <li>Your spiritual questions and concerns</li>
            <li>AI-generated responses and treatments</li>
            <li>Conversation history and context</li>
            <li>Bookmarked questions and responses</li>
          </ul>
          <p class="important-note">
            <strong>Important:</strong> All conversation data is owned by Centers for Spiritual Living (CSL) 
            and may be used for improving our services and maintaining the authenticity of Ernest Holmes' teachings.
          </p>
        </div>

        <div class="policy-item">
          <h3>Usage Information</h3>
          <p>
            We collect information about how you use Holmes AI, including:
          </p>
          <ul>
            <li>Pages visited and features used</li>
            <li>Time spent on the platform</li>
            <li>Response style preferences (Modern vs. In His Words)</li>
            <li>Error reports and performance data</li>
          </ul>
        </div>

        <div class="policy-item">
          <h3>Device Information</h3>
          <p>
            We automatically collect certain information about your device, including:
          </p>
          <ul>
            <li>IP address and general location</li>
            <li>Browser type and version</li>
            <li>Operating system</li>
            <li>Device identifiers</li>
          </ul>
        </div>
      </div>
    </section>

    <!-- How We Use Information -->
    <section class="section" aria-labelledby="use-heading">
      <h2 id="use-heading">How We Use Your Information</h2>
      <div class="policy-content">
        <div class="policy-item">
          <h3>Providing Our Services</h3>
          <p>
            We use your information to:
          </p>
          <ul>
            <li>Generate personalized spiritual guidance</li>
            <li>Maintain conversation context and history</li>
            <li>Provide bookmarking and question history features</li>
            <li>Ensure the authenticity of Ernest Holmes' voice</li>
          </ul>
        </div>

        <div class="policy-item">
          <h3>Improving Our Services</h3>
          <p>
            We use aggregated and anonymized data to:
          </p>
          <ul>
            <li>Improve AI response quality and accuracy</li>
            <li>Develop new features and capabilities</li>
            <li>Identify and fix technical issues</li>
            <li>Enhance user experience and accessibility</li>
          </ul>
        </div>

        <div class="policy-item">
          <h3>Security and Compliance</h3>
          <p>
            We use your information to:
          </p>
          <ul>
            <li>Protect against fraud and abuse</li>
            <li>Ensure compliance with legal obligations</li>
            <li>Maintain the security of our platform</li>
            <li>Investigate and resolve technical issues</li>
          </ul>
        </div>
      </div>
    </section>

    <!-- Data Ownership -->
    <section class="section" aria-labelledby="ownership-heading">
      <h2 id="ownership-heading">Data Ownership</h2>
      <div class="ownership-content">
        <div class="ownership-notice">
          <h3>Centers for Spiritual Living (CSL) Rights</h3>
          <p class="important-note">
            <strong>All data collected through Holmes AI is owned by Centers for Spiritual Living (CSL).</strong> 
            This includes, but is not limited to:
          </p>
          <ul>
            <li>All questions asked by users</li>
            <li>All AI-generated responses and treatments</li>
            <li>User conversation history and patterns</li>
            <li>Usage analytics and traffic data</li>
            <li>User preferences and interaction data</li>
          </ul>
          <p>
            CSL reserves the right to use this data for:
          </p>
          <ul>
            <li>Improving the authenticity and accuracy of Holmes AI</li>
            <li>Research and development of spiritual AI technology</li>
            <li>Understanding user needs and spiritual questions</li>
            <li>Maintaining and enhancing the platform</li>
            <li>Educational and training purposes</li>
          </ul>
        </div>
      </div>
    </section>

    <!-- Data Protection -->
    <section class="section" aria-labelledby="protection-heading">
      <h2 id="protection-heading">Data Protection</h2>
      <div class="policy-content">
        <div class="policy-item">
          <h3>Security Measures</h3>
          <p>
            We implement industry-standard security measures to protect your data:
          </p>
          <ul>
            <li>End-to-end encryption for all communications</li>
            <li>Secure data storage with access controls</li>
            <li>Regular security audits and updates</li>
            <li>Employee training on data protection</li>
          </ul>
        </div>

        <div class="policy-item">
          <h3>Data Retention</h3>
          <p>
            We retain your data for as long as necessary to:
          </p>
          <ul>
            <li>Provide our services to you</li>
            <li>Comply with legal obligations</li>
            <li>Improve our AI systems</li>
            <li>Maintain the integrity of Ernest Holmes' teachings</li>
          </ul>
        </div>
      </div>
    </section>

    <!-- Data Sharing -->
    <section class="section" aria-labelledby="sharing-heading">
      <h2 id="sharing-heading">Data Sharing</h2>
      <div class="policy-content">
        <div class="policy-item">
          <h3>We Do Not Sell Your Data</h3>
          <p class="important-note">
            <strong>Holmes AI will never sell, rent, or trade your personal data to third parties.</strong>
          </p>
          <p>
            We may share your data only in the following limited circumstances:
          </p>
          <ul>
            <li>With Centers for Spiritual Living (CSL) for service improvement</li>
            <li>With trusted service providers who assist in operating our platform</li>
            <li>When required by law or to protect our rights and safety</li>
            <li>With your explicit consent for specific purposes</li>
          </ul>
        </div>

        <div class="policy-item">
          <h3>Service Providers</h3>
          <p>
            We work with trusted third-party service providers who help us operate Holmes AI. 
            These providers are bound by strict confidentiality agreements and may only use your data 
            to provide services to us.
          </p>
        </div>
      </div>
    </section>

    <!-- Children's Privacy -->
    <section class="section" aria-labelledby="children-heading">
      <h2 id="children-heading">Children's Privacy</h2>
      <div class="policy-content">
        <div class="policy-item">
          <p>
            Holmes AI is not intended for children under the age of 13. We do not knowingly collect 
            personal information from children under 13. If you are a parent or guardian and believe 
            your child has provided us with personal information, please contact us immediately.
          </p>
        </div>
      </div>
    </section>

    <!-- International Users -->
    <section class="section" aria-labelledby="international-heading">
      <h2 id="international-heading">International Users</h2>
      <div class="policy-content">
        <div class="policy-item">
          <p>
            Holmes AI is operated from the United States. If you are accessing our service from outside 
            the United States, please be aware that your information may be transferred to, stored, and 
            processed in the United States where our servers are located.
          </p>
        </div>
      </div>
    </section>

    <!-- Policy Changes -->
    <section class="section" aria-labelledby="changes-heading">
      <h2 id="changes-heading">Changes to This Policy</h2>
      <div class="policy-content">
        <div class="policy-item">
          <p>
            We may update this Privacy Policy from time to time. We will notify you of any changes by:
          </p>
          <ul>
            <li>Posting the new Privacy Policy on this page</li>
            <li>Updating the "Last Updated" date at the bottom of this policy</li>
            <li>Sending you an email notification for significant changes</li>
          </ul>
          <p>
            We encourage you to review this Privacy Policy periodically to stay informed about how we 
            protect your information.
          </p>
        </div>
      </div>
    </section>

    <!-- Contact Information -->
    <section class="section" aria-labelledby="contact-heading">
      <h2 id="contact-heading">Contact Us</h2>
      <div class="contact-content">
        <p>
          If you have any questions about this Privacy Policy or our data practices, please contact us:
        </p>
        <div class="contact-info">
          <div class="contact-item">
            <strong>Email:</strong> <a href="mailto:privacy@holmesai.org" class="contact-link">privacy@holmesai.org</a>
          </div>
          <div class="contact-item">
            <strong>Address:</strong> Centers for Spiritual Living, 573 Park Point Drive, Golden, CO 80401
          </div>
          <div class="contact-item">
            <strong>Phone:</strong> <a href="tel:+17204961370" class="contact-link">(720) 496-1370</a>
          </div>
        </div>
      </div>
    </section>

    <!-- Last Updated -->
    <section class="section">
      <div class="last-updated">
        <p><strong>Last Updated:</strong> January 2025</p>
      </div>
    </section>
  </div>
</div>

<style>
  .privacy-page {
    background: var(--bg-primary);
    min-height: 100vh;
    color: var(--text-primary);
  }

  .hero {
    background: linear-gradient(135deg, var(--text-accent) 0%, var(--text-accent-hover) 100%);
    color: white;
    text-align: center;
    padding: 4rem 2rem;
  }

  .hero h1 {
    font-size: 3rem;
    margin-bottom: 1rem;
    color: white;
  }

  .hero-subtitle {
    font-size: 1.3rem;
    opacity: 0.9;
    color: white;
  }

  .container {
    max-width: 1000px;
    margin: 0 auto;
    padding: 0 2rem;
  }

  .section {
    padding: 3rem 0;
  }

  .section h2 {
    font-size: 2.5rem;
    text-align: center;
    margin-bottom: 3rem;
    color: var(--text-primary);
  }

  .lead {
    font-size: 1.3rem;
    font-weight: 500;
    margin-bottom: 1.5rem;
    color: var(--text-accent);
  }

  .intro-content {
    text-align: center;
    max-width: 800px;
    margin: 0 auto;
  }

  .intro-content p {
    color: var(--text-secondary);
    line-height: 1.6;
  }

  .policy-content {
    display: grid;
    gap: 2rem;
  }

  .policy-item {
    background: var(--bg-secondary);
    padding: 2rem;
    border-radius: 15px;
    box-shadow: 0 5px 15px var(--shadow-light);
    border: 1px solid var(--border-primary);
  }

  .policy-item h3 {
    color: var(--text-accent);
    margin-bottom: 1rem;
    font-size: 1.5rem;
  }

  .policy-item p {
    margin-bottom: 1rem;
    line-height: 1.6;
    color: var(--text-secondary);
  }

  .policy-item ul {
    margin: 1rem 0;
    padding-left: 1.5rem;
  }

  .policy-item li {
    margin-bottom: 0.5rem;
    line-height: 1.6;
    color: var(--text-secondary);
  }

  .important-note {
    background: rgba(251, 191, 36, 0.1);
    border-left: 4px solid var(--text-accent);
    padding: 1rem;
    margin: 1rem 0;
    border-radius: 0 5px 5px 0;
  }

  .ownership-content {
    background: var(--bg-secondary);
    padding: 2rem;
    border-radius: 15px;
    box-shadow: 0 5px 15px var(--shadow-medium);
    border: 1px solid var(--border-primary);
  }

  .ownership-notice h3 {
    color: var(--text-accent);
    margin-bottom: 1rem;
    font-size: 1.5rem;
  }

  .contact-content {
    text-align: center;
    background: var(--bg-secondary);
    padding: 2rem;
    border-radius: 15px;
    box-shadow: 0 5px 15px var(--shadow-light);
    border: 1px solid var(--border-primary);
  }

  .contact-info {
    display: grid;
    gap: 1rem;
    margin-top: 1.5rem;
  }

  .contact-item {
    padding: 1rem;
    background: var(--bg-primary);
    border-radius: 10px;
    color: var(--text-secondary);
    border: 1px solid var(--border-primary);
  }

  .contact-link {
    color: var(--text-accent);
    text-decoration: none;
    transition: color 0.3s ease;
  }

  .contact-link:hover {
    color: var(--text-accent-hover);
  }

  .contact-link:focus-visible {
    outline: 2px solid var(--focus-ring);
    outline-offset: 2px;
  }

  .last-updated {
    text-align: center;
    color: var(--text-secondary);
    font-style: italic;
  }

  @media (max-width: 768px) {
    .hero h1 {
      font-size: 2rem;
    }

    .container {
      padding: 0 1rem;
    }

    .policy-item {
      padding: 1.5rem;
    }
  }

  /* High contrast mode support */
  @media (prefers-contrast: high) {
    .policy-item,
    .ownership-content,
    .contact-content {
      border: 2px solid var(--border-primary);
    }
    
    .contact-link {
      border: 1px solid currentColor;
      padding: 0.25rem 0.5rem;
      border-radius: 3px;
    }
  }

  /* Reduced motion support */
  @media (prefers-reduced-motion: reduce) {
    .contact-link {
      transition: none;
    }
  }
</style> 